export const VOICE_CARDS = Object.freeze([
  {
    id: "blank-keeper",
    number: "I",
    name: "留白者",
    accent: "#c99591",
    vector: [0.18, 0.1, 0.12, 0.16, 0.1, 0.08],
    tagline: "讓沉默保有它的形狀",
    reading: "你的聲音懂得退後一步，讓意義在停頓之間浮現。你不急著填滿空間，因此細小的情緒反而更容易被聽見。",
    question: "如果不必立刻回答，你真正想留下的是什麼？",
    symbol: "pause",
  },
  {
    id: "fire-starter",
    number: "II",
    name: "點火者",
    accent: "#ed8e72",
    vector: [0.82, 0.78, 0.82, 0.62, 0.34, 0.95],
    tagline: "把第一束光交給世界",
    reading: "你的聲音帶著推進的熱度，能把模糊的想法點亮。當你相信一件事，節奏會先於語句抵達他人。",
    question: "此刻最值得你先踏出一步的是哪件事？",
    symbol: "spark",
  },
  {
    id: "listener",
    number: "III",
    name: "傾聽者",
    accent: "#c7a6b8",
    vector: [0.38, 0.18, 0.26, 0.1, 0.18, 0.28],
    tagline: "在靠近以前，先聽見",
    reading: "你的聲音不搶奪注意，而是建立容納感。柔和與穩定讓人願意把尚未整理好的心情交給你。",
    question: "你是否也把同樣的耐心留給自己？",
    symbol: "ear",
  },
  {
    id: "traveler",
    number: "IV",
    name: "旅行者",
    accent: "#d7a17f",
    vector: [0.68, 0.48, 0.92, 0.88, 0.26, 0.72],
    tagline: "用聲音測量未知的遠方",
    reading: "你的聲音有明顯的移動感，語句像沿著地平線尋路。變化不是不安，而是你理解世界的方法。",
    question: "下一段旅程，你想帶走什麼，又願意放下什麼？",
    symbol: "compass",
  },
  {
    id: "dream-builder",
    number: "V",
    name: "築夢者",
    accent: "#b88cae",
    vector: [0.74, 0.28, 0.48, 0.68, 0.1, 0.46],
    tagline: "為還不存在的事搭一座橋",
    reading: "你的聲音同時保有想像與秩序。明亮的輪廓讓願景可見，而溫和的推進讓它不只停在夢裡。",
    question: "哪一個反覆出現的念頭，正在等待你為它命名？",
    symbol: "arch",
  },
  {
    id: "night-keeper",
    number: "VI",
    name: "守夜人",
    accent: "#d69a81",
    vector: [0.08, 0.3, 0.08, 0.32, 0.5, 0.16],
    tagline: "在安靜裡，聽見尚未說完的事",
    reading: "你的聲音帶著夜色般的重量，不炫目，卻能陪伴。你擅長守住混亂中的微光，直到事情顯出真正的輪廓。",
    question: "有什麼需要被守護，而不是立刻被解決？",
    symbol: "moon",
  },
  {
    id: "echo-bearer",
    number: "VII",
    name: "迴響者",
    accent: "#a985a8",
    vector: [0.48, 0.42, 0.64, 0.98, 0.62, 0.52],
    tagline: "讓一句話走得比當下更遠",
    reading: "你的聲音富有空間與餘韻，容易在他人心裡留下第二次發生。你說出的不只是內容，也是一種可被記住的氣候。",
    question: "你希望今天的哪句話，在未來仍被聽見？",
    symbol: "echo",
  },
  {
    id: "wave-breaker",
    number: "VIII",
    name: "破浪者",
    accent: "#e08073",
    vector: [0.62, 0.94, 0.88, 0.72, 0.84, 0.92],
    tagline: "把阻力變成前進的節拍",
    reading: "你的聲音有清楚的稜角與動能，像船首切開水面。它不迴避摩擦，反而能在阻力中形成方向。",
    question: "哪一道浪，正邀請你證明自己的力量？",
    symbol: "wave",
  },
]);
